---

- name: build a new image for the Wordpress web site
  hosts: localhost

  vars:
     force_build: no
     download_wp: no
     push_image: yes
     image_name: "{{ lookup('ini', 'IMAGE_NAME type=properties file=../website/.env') }}"
     image_version: "{{ lookup('ini', 'VERSION type=properties file=../website/.env') }}"

  vars_prompt:
     - name: "registry_password"
       prompt: "please, enter registry password"
       private: yes

  tasks:

     - name: optionally download vanilla wordpress from source control
       git:
        repo: "https://github.com/WordPress/WordPress.git"
        dest: ../website/wordpress
       when: download_wp == "yes"

     - name: Gather context
       command: ./make_env
       args:
        chdir: ../website/

     - debug:
         msg: "image version: {{image_version}}"


     - name: login to the remote registry
       docker_login:
         registry: "{{registry_url}}"
         username: "{{registry_user}}"
         password: "{{registry_password}}"
         reauthorize: yes


     - name: Build, Tag and push to the registry
       docker_image:
         state: build
         name: "{{registry_url}}/{{ image_name }}"
         repository: "{{registry_url}}/{{ image_name }}"
         tag: "{{ image_version }}"
         path: ..
         pull: yes
         push: "{{push_image}}"
         rm: yes
         force: "{{force_build}}"
